### PR TITLE
Allow bars to hide after defined amount of seconds

### PR DESCRIPTION
**Pull request by ernierasta**
Hi!
I would like to use bar auto hiding in my UI mod (not published yet). Code I have added allows to set timeouts for HP, MP and XP bars.

HP and MP bars will disappear if they are at full state for given amount of seconds. XP bar will disappear if experience points will not change for given amount of time.

Disclaimer: This is first time I had written anything in C++, please review code carefully.

### CODE REVIEW

**Comment by dorkster** [comment]
Thanks. I made a few changes in [this commit](https://github.com/flareteam/flare-engine/commit/b7b11a10150a17a143783b2d1f54650d122e3466), which are summarized n the commit message.

I also might add an option to the config menu option so players can turn off auto-hiding if they wish to.

**Comment by dorkster** [comment]
By the way, since we use `Parse::toDuration()`, you'll need to use the proper syntax to have the timeout in seconds. So instead of:

```
hide_timeout=1
```

it would be:

```
hide_timeout=1s
```

or

```
hide_timeout=1000ms
```

**Comment by ernierasta** [comment]
Great! Thank you for merge, edits and info!

I was also thinking about adding option to make bar visible only after some every percentage filled. This would allow for example: 
- show XP bar only on 0, 25,50,75.100%, bar could have some visual effects on those spots ...

But I will have to experiment with it if it makes any sense.

**Comment by ernierasta** [comment]
And a side note: 
My first implementation was based on setting in settings.txt file, but the problem was, that it usually convenient to have longer XP bar timeout than HP,MP which can hide quite quickly. XP if hidden too fast will often "blink" when killing enemies.

**Pull request merged**
